version: "3"
services:
  signal:
    # image: bbernhard/signal-cli-rest-api:latest
    build:
      context: ../
      dockerfile: signal-cli-rest-api/Dockerfile
    environment:
      - MODE=native #supported modes: json-rpc, native, normal
      #- AUTO_RECEIVE_SCHEDULE=0 22 * * * #enable this parameter on demand (see description below)
    ports:
      - "8080:8080" #map docker port 8080 to host port 8080.
    volumes:
      - "../tip-crawlers-v2/cf/services/signal/signal:/home/.local/share/signal-cli" #map "signal-cli-config" folder on host system into docker container. the folder contains the password and cryptographic keys when a new number is registered
